### PR TITLE
A few changes

### PR DESCRIPTION
**Pull request by GaelVaroquaux**
I made a few minor changes. I've removed one of the images (less is more), but by doing so, I've broken a bit the layout. Please have a look and fix it :).

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
> Merged #3.

The layout is broken below the line of images. I didn't know how to fix
it. Can you have a look please.

**Comment by GaelVaroquaux** [comment]
The breakage is visible only if you increase the fonts, by the way.

**Comment by glemaitre** [comment]
It should be solved

**Comment by GaelVaroquaux** [comment]
Indeed. Thanks!

**Pull request merged**
